// Fragen hier anpassen. Jeder Eintrag: question und answer.
window.PUB_QUIZ_QUESTIONS = [
  { question: "Was ist die Hauptstadt von Frankreich?", answer: "Paris" },
  { question: "Wie viele Kontinente gibt es?", answer: "Sieben" },
  { question: "In welchem Jahr endete der Erste Weltkrieg?", answer: "1918" },
  { question: "Welcher Planet wird der Rote Planet genannt?", answer: "Mars" },
  { question: "Welcher Ozean ist der größte der Erde?", answer: "Pazifik" },
  { question: "Wer schrieb Romeo und Julia?", answer: "William Shakespeare" },
  { question: "Was ist das chemische Symbol für Gold?", answer: "Au" },
  { question: "In welchem Land steht das Taj Mahal?", answer: "Indien" },
  { question: "Was ist die kleinste Primzahl?", answer: "2" },
  { question: "Welche Band sang 'Bohemian Rhapsody'?", answer: "Queen" },
  { question: "Wo fährt die Familie in „Kevin – Allein zu Haus" in den Urlaub, als sie Kevin zurücklässt?", answer: "Paris" },
  { question: "In welchem heutigen Land wurde der Heilige Nikolaus geboren?", answer: "Türkei" },
  { question: "Welcher Schokoladenriegel ist weltweit der Verkaufsschlager?", answer: "Snickers" },
  { question: "Welches Gebäck wird traditionell kopfüber gebacken?", answer: "Tarte Tatin" },
  { question: "Welcher Hollywood-Schauspieler spielte sechs verschiedene Rollen in „Der Polarexpress"?", answer: "Tom Hanks" },
  { question: "Wer gilt als Begründer:in von Demeter (dem Qualitätslabel)?", answer: "Rudolf Steiner" },
  { question: "Welches Weihnachtsballett wurde 1892 uraufgeführt?", answer: "Der Nussknacker" },
  { question: "Migros betrieb in den 1980er-Jahren eine Fast-Food-Kette. Wie hiess sie?", answer: "Migrolino" },
  { question: "Welche Organisation ging mit ihrer Topfkollekte in die Liste der „Gelebten Berner Traditionen" ein?", answer: "Heilsarmee" },
  { question: "Wie heisst der Hund des Grinch?", answer: "Max" },
];
